/*
 * Copyright (C) 2025 ModSeeker
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

// ============================================================================
// OpenSSL-based Cryptographic Vault for Hidder Mod
// Replaces Windows CNG with OpenSSL for Java compatibility
// ============================================================================

#include <jni.h>
#include <string>
#include <vector>
#include <cstring>
#include <fstream>
#include <sstream>
#include <iomanip>

// OpenSSL Headers
#include <openssl/rsa.h>
#include <openssl/pem.h>
#include <openssl/evp.h>
#include <openssl/rand.h>
#include <openssl/err.h>
#include <openssl/bn.h>
#include <openssl/hmac.h>


#include <windows.h>
#include <tlhelp32.h>
#include <algorithm>
#include <cctype>

// Windows types for compatibility
typedef unsigned char BYTE;


// --- Base64 Utilities ---
static const std::string base64_chars =
    "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
    "abcdefghijklmnopqrstuvwxyz"
    "0123456789+/";

std::vector<BYTE> base64_decode(std::string const& encoded_string) {
    int in_len = encoded_string.size();
    int i = 0;
    int j = 0;
    int in_ = 0;
    BYTE char_array_4[4], char_array_3[3];
    std::vector<BYTE> ret;

    while (in_len-- && (encoded_string[in_] != '=') &&
           (isalnum(encoded_string[in_]) || (encoded_string[in_] == '+') || (encoded_string[in_] == '/'))) {
        char_array_4[i++] = encoded_string[in_];
        in_++;
        if (i == 4) {
            for (i = 0; i < 4; i++)
                char_array_4[i] = base64_chars.find(char_array_4[i]);

            char_array_3[0] = (char_array_4[0] << 2) + ((char_array_4[1] & 0x30) >> 4);
            char_array_3[1] = ((char_array_4[1] & 0xf) << 4) + ((char_array_4[2] & 0x3c) >> 2);
            char_array_3[2] = ((char_array_4[2] & 0x3) << 6) + char_array_4[3];

            for (i = 0; i < 3; i++)
                ret.push_back(char_array_3[i]);
            i = 0;
        }
    }

    if (i) {
        for (j = i; j < 4; j++)
            char_array_4[j] = 0;

        for (j = 0; j < 4; j++)
            char_array_4[j] = base64_chars.find(char_array_4[j]);

        char_array_3[0] = (char_array_4[0] << 2) + ((char_array_4[1] & 0x30) >> 4);
        char_array_3[1] = ((char_array_4[1] & 0xf) << 4) + ((char_array_4[2] & 0x3c) >> 2);
        char_array_3[2] = ((char_array_4[2] & 0x3) << 6) + char_array_4[3];

        for (j = 0; j < i - 1; j++)
            ret.push_back(char_array_3[j]);
    }

    return ret;
}

std::string base64_encode(const BYTE* bytes_to_encode, unsigned int in_len) {
    std::string ret;
    int i = 0;
    int j = 0;
    BYTE char_array_3[3];
    BYTE char_array_4[4];

    while (in_len--) {
        char_array_3[i++] = *(bytes_to_encode++);
        if (i == 3) {
            char_array_4[0] = (char_array_3[0] & 0xfc) >> 2;
            char_array_4[1] = ((char_array_3[0] & 0x03) << 4) + ((char_array_3[1] & 0xf0) >> 4);
            char_array_4[2] = ((char_array_3[1] & 0x0f) << 2) + ((char_array_3[2] & 0xc0) >> 6);
            char_array_4[3] = char_array_3[2] & 0x3f;

            for (i = 0; i < 4; i++)
                ret += base64_chars[char_array_4[i]];
            i = 0;
        }
    }

    if (i) {
        for (j = i; j < 3; j++)
            char_array_3[j] = '\0';

        char_array_4[0] = (char_array_3[0] & 0xfc) >> 2;
        char_array_4[1] = ((char_array_3[0] & 0x03) << 4) + ((char_array_3[1] & 0xf0) >> 4);
        char_array_4[2] = ((char_array_3[1] & 0x0f) << 2) + ((char_array_3[2] & 0xc0) >> 6);
        char_array_4[3] = char_array_3[2] & 0x3f;

        for (j = 0; j < i + 1; j++)
            ret += base64_chars[char_array_4[j]];

        while (i++ < 3)
            ret += '=';
    }

    return ret;
}

// ============================================================================
// RSA KEY COMPONENTS
// ============================================================================

// --- CLIENT RSA Key Components (For Signing) ---
// PLACEHOLDER: Replace with values from CLIENT_KEYS_CPP.txt (generated by ModSeeker/Tools/KeyGen.java)
const std::string B64_MODULUS = "REPLACE_WITH_VALUE_FROM_KEYGEN";
const std::string B64_PUB_EXP = "REPLACE_WITH_VALUE_FROM_KEYGEN";
const std::string B64_PRIV_EXP = "REPLACE_WITH_VALUE_FROM_KEYGEN";
const std::string B64_PRIME1 = "REPLACE_WITH_VALUE_FROM_KEYGEN";
const std::string B64_PRIME2 = "REPLACE_WITH_VALUE_FROM_KEYGEN";
const std::string B64_EXP1 = "REPLACE_WITH_VALUE_FROM_KEYGEN";
const std::string B64_EXP2 = "REPLACE_WITH_VALUE_FROM_KEYGEN";
const std::string B64_COEFF = "REPLACE_WITH_VALUE_FROM_KEYGEN";

// --- SERVER RSA Key Components (For Encryption) ---
// PLACEHOLDER: Replace with values from CLIENT_KEYS_CPP.txt (generated by ModSeeker/Tools/KeyGen.java)
const std::string SRV_B64_MODULUS = "REPLACE_WITH_VALUE_FROM_KEYGEN";
const std::string SRV_B64_EXP = "REPLACE_WITH_VALUE_FROM_KEYGEN";

// ============================================================================
// OpenSSL Key Handles (Global)
// ============================================================================
EVP_PKEY* pClientKey = NULL;  // Client private key for signing
EVP_PKEY* pServerKey = NULL;  // Server public key for encryption

// ============================================================================
// Initialize Keys using OpenSSL
// ============================================================================
void InitializeKeys() {
    if (pClientKey != NULL && pServerKey != NULL) return;

    // --- Import Client Private Key (For Signing) ---
    if (pClientKey == NULL) {
        auto modBytes = base64_decode(B64_MODULUS);
        auto pubExpBytes = base64_decode(B64_PUB_EXP);
        auto privExpBytes = base64_decode(B64_PRIV_EXP);
        auto p1Bytes = base64_decode(B64_PRIME1);
        auto p2Bytes = base64_decode(B64_PRIME2);
        auto e1Bytes = base64_decode(B64_EXP1);
        auto e2Bytes = base64_decode(B64_EXP2);
        auto coeffBytes = base64_decode(B64_COEFF);

        // Strip leading zero if present (Java BigInteger sign byte)
        if (modBytes.size() == 257 && modBytes[0] == 0) modBytes.erase(modBytes.begin());
        if (privExpBytes.size() == 257 && privExpBytes[0] == 0) privExpBytes.erase(privExpBytes.begin());
        if (p1Bytes.size() == 129 && p1Bytes[0] == 0) p1Bytes.erase(p1Bytes.begin());
        if (p2Bytes.size() == 129 && p2Bytes[0] == 0) p2Bytes.erase(p2Bytes.begin());
        if (e1Bytes.size() == 129 && e1Bytes[0] == 0) e1Bytes.erase(e1Bytes.begin());
        if (e2Bytes.size() == 129 && e2Bytes[0] == 0) e2Bytes.erase(e2Bytes.begin());
        if (coeffBytes.size() == 129 && coeffBytes[0] == 0) coeffBytes.erase(coeffBytes.begin());

        // Create BIGNUM objects from byte arrays
        BIGNUM* n = BN_bin2bn(modBytes.data(), modBytes.size(), NULL);
        BIGNUM* e = BN_bin2bn(pubExpBytes.data(), pubExpBytes.size(), NULL);
        BIGNUM* d = BN_bin2bn(privExpBytes.data(), privExpBytes.size(), NULL);
        BIGNUM* p = BN_bin2bn(p1Bytes.data(), p1Bytes.size(), NULL);
        BIGNUM* q = BN_bin2bn(p2Bytes.data(), p2Bytes.size(), NULL);
        BIGNUM* dmp1 = BN_bin2bn(e1Bytes.data(), e1Bytes.size(), NULL);
        BIGNUM* dmq1 = BN_bin2bn(e2Bytes.data(), e2Bytes.size(), NULL);
        BIGNUM* iqmp = BN_bin2bn(coeffBytes.data(), coeffBytes.size(), NULL);

        // Create RSA key and set components
        RSA* rsa = RSA_new();
        RSA_set0_key(rsa, n, e, d);
        RSA_set0_factors(rsa, p, q);
        RSA_set0_crt_params(rsa, dmp1, dmq1, iqmp);

        // Create EVP_PKEY from RSA
        pClientKey = EVP_PKEY_new();
        EVP_PKEY_assign_RSA(pClientKey, rsa);
    }

    // --- Import Server Public Key (For Encryption) ---
    if (pServerKey == NULL) {
        auto modBytes = base64_decode(SRV_B64_MODULUS);
        auto expBytes = base64_decode(SRV_B64_EXP);

        // Strip leading zero if present
        if (modBytes.size() == 257 && modBytes[0] == 0) modBytes.erase(modBytes.begin());

        // Create BIGNUM objects
        BIGNUM* n = BN_bin2bn(modBytes.data(), modBytes.size(), NULL);
        BIGNUM* e = BN_bin2bn(expBytes.data(), expBytes.size(), NULL);

        // Create RSA key (public only)
        RSA* rsa = RSA_new();
        RSA_set0_key(rsa, n, e, NULL);  // NULL for private exponent (public key only)

        // Create EVP_PKEY from RSA
        pServerKey = EVP_PKEY_new();
        EVP_PKEY_assign_RSA(pServerKey, rsa);
    }
}

// ============================================================================
// JNI Exported Functions
// ============================================================================
extern "C" {

    // --- Sign Function ---
    JNIEXPORT jstring JNICALL Java_com_example_hidder_NativeBridge_sign(JNIEnv* env, jclass clazz, jstring data) {
        InitializeKeys();
        if (pClientKey == NULL) {
            return env->NewStringUTF("ERROR_KEY_INIT");
        }

        const char* dataChars = env->GetStringUTFChars(data, nullptr);
        std::string dataStr(dataChars);
        env->ReleaseStringUTFChars(data, dataChars);

        // Create signing context
        EVP_MD_CTX* mdCtx = EVP_MD_CTX_new();
        EVP_DigestSignInit(mdCtx, NULL, EVP_sha256(), NULL, pClientKey);
        EVP_DigestSignUpdate(mdCtx, dataStr.c_str(), dataStr.length());

        // Get signature length
        size_t sigLen = 0;
        EVP_DigestSignFinal(mdCtx, NULL, &sigLen);

        // Get signature
        std::vector<BYTE> signature(sigLen);
        EVP_DigestSignFinal(mdCtx, signature.data(), &sigLen);
        EVP_MD_CTX_free(mdCtx);

        std::string b64Sig = base64_encode(signature.data(), sigLen);
        return env->NewStringUTF(b64Sig.c_str());
    }

    // --- Encrypt Function ---
    JNIEXPORT jstring JNICALL Java_com_example_hidder_NativeBridge_encrypt(JNIEnv* env, jclass clazz, jstring data) {

        InitializeKeys();

        if (pServerKey == NULL) {

            return env->NewStringUTF("ERROR_SRV_KEY_INIT");
        }

        // 1. Generate AES Session Key (32 bytes for AES-256)
        BYTE aesKey[32];
        if (RAND_bytes(aesKey, 32) != 1) {

            return env->NewStringUTF("ERROR_RNG");
        }


        // 2. Encrypt AES Key with Server RSA Public Key (PKCS#1 v1.5 padding)
        EVP_PKEY_CTX* rsaCtx = EVP_PKEY_CTX_new(pServerKey, NULL);
        EVP_PKEY_encrypt_init(rsaCtx);
        EVP_PKEY_CTX_set_rsa_padding(rsaCtx, RSA_PKCS1_PADDING);

        // Get encrypted key length
        size_t encryptedKeyLen = 0;
        EVP_PKEY_encrypt(rsaCtx, NULL, &encryptedKeyLen, aesKey, 32);

        // Encrypt the AES key
        std::vector<BYTE> encryptedAesKey(encryptedKeyLen);
        if (EVP_PKEY_encrypt(rsaCtx, encryptedAesKey.data(), &encryptedKeyLen, aesKey, 32) <= 0) {

            EVP_PKEY_CTX_free(rsaCtx);
            return env->NewStringUTF("ERROR_RSA_ENCRYPT");
        }
        EVP_PKEY_CTX_free(rsaCtx);



        // 3. Get plaintext data from Java
        const char* dataChars = env->GetStringUTFChars(data, nullptr);
        std::string plainText(dataChars);
        env->ReleaseStringUTFChars(data, dataChars);



        // 4. Generate random IV (16 bytes for AES-CBC)
        BYTE iv[16];
        RAND_bytes(iv, 16);
        BYTE ivCopy[16];
        memcpy(ivCopy, iv, 16);  // Keep copy for output (encryption modifies IV)

        // 5. Encrypt data with AES-256-CBC using OpenSSL EVP
        EVP_CIPHER_CTX* aesCtx = EVP_CIPHER_CTX_new();
        EVP_EncryptInit_ex(aesCtx, EVP_aes_256_cbc(), NULL, aesKey, iv);

        // EVP handles PKCS7 padding automatically
        int outLen = 0;
        int finalLen = 0;
        std::vector<BYTE> encryptedData(plainText.length() + EVP_MAX_BLOCK_LENGTH);

        EVP_EncryptUpdate(aesCtx, encryptedData.data(), &outLen,
                          (const unsigned char*)plainText.c_str(), plainText.length());
        int totalLen = outLen;

        EVP_EncryptFinal_ex(aesCtx, encryptedData.data() + outLen, &finalLen);
        totalLen += finalLen;

        EVP_CIPHER_CTX_free(aesCtx);

        // Resize to actual encrypted length
        encryptedData.resize(totalLen);

        std::string finalOutput = base64_encode(encryptedAesKey.data(), encryptedKeyLen) + "|" +
                                  base64_encode(ivCopy, 16) + "|" +
                                  base64_encode(encryptedData.data(), totalLen);

        return env->NewStringUTF(finalOutput.c_str());
    }

    JNIEXPORT jstring JNICALL Java_com_example_hidder_NativeBridge_signBeacon(JNIEnv* env, jclass clazz, jlong timestamp) {
        InitializeKeys();
        if (pClientKey == NULL) {
            return env->NewStringUTF("ERROR_KEY_INIT");
        }

        std::string timestampStr = std::to_string(timestamp);
        
        EVP_MD_CTX* mdCtx = EVP_MD_CTX_new();
        EVP_DigestSignInit(mdCtx, NULL, EVP_sha256(), NULL, pClientKey);
        EVP_DigestSignUpdate(mdCtx, timestampStr.c_str(), timestampStr.length());

        size_t sigLen = 0;
        EVP_DigestSignFinal(mdCtx, NULL, &sigLen);

        std::vector<BYTE> signature(sigLen);
        EVP_DigestSignFinal(mdCtx, signature.data(), &sigLen);
        EVP_MD_CTX_free(mdCtx);

        std::string sigB64 = base64_encode(signature.data(), sigLen);
        return env->NewStringUTF(sigB64.c_str());
    }

    JNIEXPORT jstring JNICALL Java_com_example_hidder_NativeBridge_computeHmac(JNIEnv* env, jclass clazz, jstring nonce) {
        const char* nonceChars = env->GetStringUTFChars(nonce, nullptr);
        std::string nonceStr(nonceChars);
        env->ReleaseStringUTFChars(nonce, nonceChars);

        // XOR-encoded HMAC key — decoded at runtime to prevent string extraction
        // PLACEHOLDER: Replace this entire block with the contents of HMAC_SECRET_CPP.txt
        //              (generated by ModSeeker/Tools/KeyGen.java)
        // The array below is a placeholder — it will NOT work until replaced with real keys.
        static const unsigned char ENCODED_HMAC_KEY[] = {
            0x00  // REPLACE: Paste XOR-encoded bytes from HMAC_SECRET_CPP.txt
        };
        const int HMAC_KEY_LEN = 32; // REPLACE: Update to match your key length from KeyGen
        unsigned char hmacKey[HMAC_KEY_LEN + 1];
        for (int i = 0; i < HMAC_KEY_LEN; i++) {
            hmacKey[i] = ENCODED_HMAC_KEY[i] ^ 0x5A;
        }
        hmacKey[HMAC_KEY_LEN] = '\0';

        unsigned int hmacLen = 0;
        unsigned char hmac[EVP_MAX_MD_SIZE];

        HMAC(EVP_sha256(), hmacKey, HMAC_KEY_LEN, 
             (const unsigned char*)nonceStr.c_str(), nonceStr.length(), 
             hmac, &hmacLen);

        // Zero the decoded key from memory
        memset(hmacKey, 0, sizeof(hmacKey));

        std::string hmacB64 = base64_encode(hmac, hmacLen);
        return env->NewStringUTF(hmacB64.c_str());
    }




    static std::string wideToLowerString(const wchar_t* wstr) {
        if (!wstr) return "";
        int len = WideCharToMultiByte(CP_UTF8, 0, wstr, -1, nullptr, 0, nullptr, nullptr);
        if (len <= 0) return "";
        std::string str(len - 1, '\0');
        WideCharToMultiByte(CP_UTF8, 0, wstr, -1, &str[0], len, nullptr, nullptr);
        std::transform(str.begin(), str.end(), str.begin(),
            [](unsigned char c) { return std::tolower(c); });
        return str;
    }


    static std::string toLower(const std::string& s) {
        std::string result = s;
        std::transform(result.begin(), result.end(), result.begin(),
            [](unsigned char c) { return std::tolower(c); });
        return result;
    }

    static std::string extractJvmProperty(const std::string& cmdLine, const std::string& propName) {
        std::string search1 = "-d" + toLower(propName) + "=";
        std::string lowerCmd = toLower(cmdLine);
        
        size_t pos = lowerCmd.find(search1);
        if (pos == std::string::npos) return "";
        
        pos += search1.length();
        
        size_t end = pos;
        if (end < cmdLine.length() && cmdLine[end] == '"') {
            end++;
            while (end < cmdLine.length() && cmdLine[end] != '"') end++;
            return cmdLine.substr(pos + 1, end - pos - 1);
        }

        while (end < cmdLine.length() && cmdLine[end] != ' ' && cmdLine[end] != ',' && cmdLine[end] != '\t') {
            end++;
        }
        return cmdLine.substr(pos, end - pos);
    }


    static std::string extractGameDir(const std::string& cmdLine) {
        std::string lowerCmd = toLower(cmdLine);
        size_t pos = lowerCmd.find("--gamedir");
        if (pos == std::string::npos) return "";
        
        pos += 9; // length of "--gamedir"

        while (pos < cmdLine.length() && (cmdLine[pos] == '=' || cmdLine[pos] == ' ' || cmdLine[pos] == ',')) {
            pos++;
        }
        
        size_t end = pos;
        if (end < cmdLine.length() && cmdLine[end] == '"') {
            end++;
            while (end < cmdLine.length() && cmdLine[end] != '"') end++;
            return cmdLine.substr(pos + 1, end - pos - 1);
        }
        while (end < cmdLine.length() && cmdLine[end] != ' ' && cmdLine[end] != ',' && cmdLine[end] != '\t') {
            end++;
        }
        return cmdLine.substr(pos, end - pos);
    }


    static DWORD getParentPID() {
        DWORD pid = GetCurrentProcessId();
        HANDLE hSnapshot = CreateToolhelp32Snapshot(TH32CS_SNAPPROCESS, 0);
        if (hSnapshot == INVALID_HANDLE_VALUE) return 0;

        PROCESSENTRY32W pe;
        pe.dwSize = sizeof(pe);

        DWORD parentPid = 0;
        if (Process32FirstW(hSnapshot, &pe)) {
            do {
                if (pe.th32ProcessID == pid) {
                    parentPid = pe.th32ParentProcessID;
                    break;
                }
            } while (Process32NextW(hSnapshot, &pe));
        }
        CloseHandle(hSnapshot);
        return parentPid;
    }


    static std::string getProcessName(DWORD pid) {
        if (pid == 0) return "";
        HANDLE hSnapshot = CreateToolhelp32Snapshot(TH32CS_SNAPPROCESS, 0);
        if (hSnapshot == INVALID_HANDLE_VALUE) return "";

        PROCESSENTRY32W pe;
        pe.dwSize = sizeof(pe);

        std::string name = "";
        if (Process32FirstW(hSnapshot, &pe)) {
            do {
                if (pe.th32ProcessID == pid) {
                    name = wideToLowerString(pe.szExeFile);
                    break;
                }
            } while (Process32NextW(hSnapshot, &pe));
        }
        CloseHandle(hSnapshot);
        return name;
    }


    static std::string getProcessPath(DWORD pid) {
        if (pid == 0) return "";
        HANDLE hProcess = OpenProcess(PROCESS_QUERY_LIMITED_INFORMATION, FALSE, pid);
        if (!hProcess) return "";

        wchar_t path[MAX_PATH] = { 0 };
        DWORD pathLen = MAX_PATH;
        std::string result = "";
        if (QueryFullProcessImageNameW(hProcess, 0, path, &pathLen)) {
            result = wideToLowerString(path);
        }
        CloseHandle(hProcess);
        return result;
    }


    static std::string matchBrandToLauncher(const std::string& brand) {
        if (brand.empty()) return "";
        std::string b = toLower(brand);


        if (b.find("atlauncher") != std::string::npos)  return "atlauncher";
        if (b.find("prism") != std::string::npos)       return "prism";
        if (b.find("curseforge") != std::string::npos)  return "curseforge";
        if (b.find("multimc") != std::string::npos)     return "multimc";
        if (b.find("modrinth") != std::string::npos)    return "modrinth";
        if (b.find("gdlauncher") != std::string::npos)  return "gdlauncher";
        if (b.find("technic") != std::string::npos)     return "technic";
        if (b.find("ftb") != std::string::npos)         return "ftb";
        if (b.find("lunar") != std::string::npos)       return "lunar";
        if (b.find("badlion") != std::string::npos)     return "badlion";
        if (b.find("feather") != std::string::npos)     return "feather";
        if (b.find("labymod") != std::string::npos)     return "labymod";
        if (b.find("tlauncher") != std::string::npos)   return "tlauncher";
        if (b.find("sklauncher") != std::string::npos)  return "sklauncher";
        if (b.find("skl") != std::string::npos)         return "sklauncher";

        return "";
    }


    static std::string matchProcessToLauncher(const std::string& processName, const std::string& processPath) {
        if (processName.empty()) return "";
        std::string p = toLower(processName);
        std::string pp = toLower(processPath);


        if (p.find("atlauncher") != std::string::npos)       return "atlauncher";
        if (p.find("prismlauncher") != std::string::npos)    return "prism";
        if (p.find("curseforge") != std::string::npos)       return "curseforge";
        if (p.find("multimc") != std::string::npos)          return "multimc";
        if (p.find("modrinth") != std::string::npos)         return "modrinth";
        if (p.find("gdlauncher") != std::string::npos)       return "gdlauncher";
        if (p.find("technic") != std::string::npos)          return "technic";
        if (p.find("ftb") != std::string::npos)              return "ftb";
        if (p.find("lunar") != std::string::npos)            return "lunar";
        if (p.find("badlion") != std::string::npos)          return "badlion";
        if (p.find("feather") != std::string::npos)          return "feather";
        if (p.find("labymod") != std::string::npos)          return "labymod";
        if (p.find("tlauncher") != std::string::npos)        return "tlauncher";
        if (p.find("sklauncher") != std::string::npos)       return "sklauncher";


        if (!pp.empty()) {
            if (pp.find("atlauncher") != std::string::npos)       return "atlauncher";
            if (pp.find("prismlauncher") != std::string::npos)    return "prism";
            if (pp.find("curseforge") != std::string::npos)       return "curseforge";
            if (pp.find("multimc") != std::string::npos)          return "multimc";
            if (pp.find("modrinth") != std::string::npos)         return "modrinth";
            if (pp.find("gdlauncher") != std::string::npos)       return "gdlauncher";
            if (pp.find("technic") != std::string::npos)          return "technic";
            if (pp.find("ftba") != std::string::npos)             return "ftb";
            if (pp.find("feed the beast") != std::string::npos)   return "ftb";
            if (pp.find("lunar") != std::string::npos)            return "lunar";
            if (pp.find("badlion") != std::string::npos)          return "badlion";
            if (pp.find("feather") != std::string::npos)          return "feather";
            if (pp.find("labymod") != std::string::npos)          return "labymod";
            if (pp.find("tlauncher") != std::string::npos)        return "tlauncher";
            if (pp.find("sklauncher") != std::string::npos)       return "sklauncher";
        }

        return "";
    }


    static std::string matchPathToLauncher(const std::string& gameDir) {
        if (gameDir.empty()) return "";
        std::string gd = toLower(gameDir);

        if (gd.find("atlauncher") != std::string::npos)         return "atlauncher";
        if (gd.find("prismlauncher") != std::string::npos)      return "prism";
        if (gd.find(".prismlauncher") != std::string::npos)     return "prism";
        if (gd.find("curseforge") != std::string::npos)         return "curseforge";
        if (gd.find("multimc") != std::string::npos)            return "multimc";
        if (gd.find(".multimc") != std::string::npos)           return "multimc";
        if (gd.find("com.modrinth") != std::string::npos)       return "modrinth";
        if (gd.find("modrinth") != std::string::npos)           return "modrinth";
        if (gd.find("gdlauncher") != std::string::npos)         return "gdlauncher";
        if (gd.find(".technic") != std::string::npos)           return "technic";
        if (gd.find("technic") != std::string::npos)            return "technic";
        if (gd.find(".ftba") != std::string::npos)              return "ftb";
        if (gd.find("ftb app") != std::string::npos)            return "ftb";
        if (gd.find("feed the beast") != std::string::npos)     return "ftb";
        if (gd.find(".lunarclient") != std::string::npos)       return "lunar";
        if (gd.find("lunarclient") != std::string::npos)        return "lunar";
        if (gd.find("badlion") != std::string::npos)            return "badlion";
        if (gd.find("feather") != std::string::npos)            return "feather";
        if (gd.find("labymod") != std::string::npos)            return "labymod";
        if (gd.find(".tlauncher") != std::string::npos)         return "tlauncher";
        if (gd.find("tlauncher") != std::string::npos)          return "tlauncher";
        if (gd.find("sklauncher") != std::string::npos)         return "sklauncher";

        return "";
    }

    JNIEXPORT jstring JNICALL Java_com_example_hidder_NativeBridge_detectLauncher(JNIEnv* env, jclass clazz) {
        std::string result = "";

        {
            wchar_t* cmdLineW = GetCommandLineW();
            std::string cmdLine = wideToLowerString(cmdLineW);
            

            std::string brand = extractJvmProperty(cmdLine, "minecraft.launcher.brand");
            if (!brand.empty()) {
                result = matchBrandToLauncher(brand);
                if (!result.empty()) {
                    return env->NewStringUTF(result.c_str());
                }
            }


            std::string fabricBrand = extractJvmProperty(cmdLine, "fabric.launcher.brand");
            if (!fabricBrand.empty()) {
                result = matchBrandToLauncher(fabricBrand);
                if (!result.empty()) {
                    return env->NewStringUTF(result.c_str());
                }
            }
        }


        {

            const char* prismId = getenv("PRISM_INST_ID");
            if (prismId != nullptr) {
                return env->NewStringUTF("prism");
            }


            const char* instId = getenv("INST_ID");
            if (instId != nullptr) {

                const char* prismDir = getenv("PRISM_INST_DIR");
                if (prismDir != nullptr) {
                    return env->NewStringUTF("prism");
                }
                return env->NewStringUTF("multimc");
            }


            const char* curseDir = getenv("CURSEFORGE_INSTALL_DIR");
            if (curseDir != nullptr) {
                return env->NewStringUTF("curseforge");
            }


            const char* ftbDir = getenv("FTB_PACK_ID");
            if (ftbDir != nullptr) {
                return env->NewStringUTF("ftb");
            }
        }


        {
            DWORD parentPid = getParentPID();
            if (parentPid != 0) {
                std::string parentName = getProcessName(parentPid);
                std::string parentPath = getProcessPath(parentPid);


                if (parentName.find("java") != std::string::npos) {
                    DWORD grandparentPid = 0;
                    HANDLE hSnap = CreateToolhelp32Snapshot(TH32CS_SNAPPROCESS, 0);
                    if (hSnap != INVALID_HANDLE_VALUE) {
                        PROCESSENTRY32W pe;
                        pe.dwSize = sizeof(pe);
                        if (Process32FirstW(hSnap, &pe)) {
                            do {
                                if (pe.th32ProcessID == parentPid) {
                                    grandparentPid = pe.th32ParentProcessID;
                                    break;
                                }
                            } while (Process32NextW(hSnap, &pe));
                        }
                        CloseHandle(hSnap);
                    }
                    if (grandparentPid != 0) {
                        parentName = getProcessName(grandparentPid);
                        parentPath = getProcessPath(grandparentPid);
                    }
                }

                result = matchProcessToLauncher(parentName, parentPath);
                if (!result.empty()) {
                    return env->NewStringUTF(result.c_str());
                }
            }
        }


        {
            wchar_t* cmdLineW = GetCommandLineW();
            std::string cmdLine = wideToLowerString(cmdLineW);
            

            std::string gameDir = extractGameDir(cmdLine);
            if (!gameDir.empty()) {
                result = matchPathToLauncher(gameDir);
                if (!result.empty()) {
                    return env->NewStringUTF(result.c_str());
                }
            }


            result = matchPathToLauncher(cmdLine);
            if (!result.empty()) {
                return env->NewStringUTF(result.c_str());
            }
        }

        return env->NewStringUTF("unknown");
    }
}
